# Generated by Django 4.1 on 2023-11-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    def reorder(apps, schema_editor):
        MyModel = apps.get_model("main_page", "Slider")
        for order, item in enumerate(MyModel.objects.all(), 1):
            item.my_order = order
            item.save(update_fields=['my_order'])

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='slider',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
